CREATE DATABASE $MYDB_NAME;
CREATE USER '$MYDB_USER'@'%' IDENTIFIED BY '$MYDB_PASSWORD';
GRANT ALL PRIVILEGES ON $MYDB_NAME.* TO '$MYDB_USER'@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYDB_ROOT_PASSWORD';
